---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:novaferrydianto/k8s.git
  sshPrivateKey: "REDACTED"
  insecure: "false"
  enableLfs: "true"