name: Build and Push App to ECR

# TODO: Update the following variables:
env:
  AWS_REGION: us-east-1
  AWS_IAM_ROLE: arn:aws:iam::424432388155:role/github-actions

on:
  workflow_dispatch:
#  push:
#    branches:
#    - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_IAM_ROLE }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Release new version
      id: release
      run: |
        bash ./scripts/git_update.sh -v patch

    - name: Add app version (Optional)
      run: echo ${{ steps.release.outputs.new-tag }} > version.txt

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ github.repository }}
        IMAGE_TAG: ${{ steps.release.outputs.new-tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG